{{- if .Values.pdb.enabled }}
{{- range $name := list "api" "frontend" "worker-poller" "worker-topology" "worker-report" "telemetry-receiver" "worker-alarm" "worker-discovery" "worker-telemetry" }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "nms-custom.name" $ }}-{{ $name }}
  labels:
    {{- include "nms-custom.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
spec:
  minAvailable: {{ $.Values.pdb.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ $name }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
---
{{- end }}
{{- end }}
