"""baseline schema

Revision ID: d861265823a6
Revises: 
Create Date: 2026-05-16 20:53:40.206134

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd861265823a6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alarm_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('match_field', sa.String(length=50), nullable=False),
    sa.Column('match_operator', sa.String(length=30), nullable=False),
    sa.Column('match_pattern', sa.String(length=512), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('message_template', sa.Text(), nullable=True),
    sa.Column('correlation_key_template', sa.String(length=255), nullable=True),
    sa.Column('auto_clear', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alarm_rules_enabled_priority', 'alarm_rules', ['enabled', 'priority'], unique=False)
    op.create_index('ix_alarm_rules_source_type', 'alarm_rules', ['source_type'], unique=False)
    op.create_table('app_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('built_in', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_roles_name'), 'app_roles', ['name'], unique=True)
    op.create_table('app_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('role', sa.String(length=512), nullable=False),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.Column('custom_permissions', sa.JSON(), nullable=False),
    sa.Column('virtual_domain', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('force_password_change', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_users_username'), 'app_users', ['username'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('object_type', sa.String(length=100), nullable=True),
    sa.Column('object_id', sa.String(length=255), nullable=True),
    sa.Column('outcome', sa.String(length=30), nullable=False),
    sa.Column('source_ip', sa.String(length=64), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_actor_action', 'audit_log', ['actor', 'action'], unique=False)
    op.create_index('ix_audit_log_object', 'audit_log', ['object_type', 'object_id'], unique=False)
    op.create_index('ix_audit_log_timestamp', 'audit_log', ['timestamp'], unique=False)
    op.create_table('credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('auth_key', sa.String(length=512), nullable=False),
    sa.Column('enc_key', sa.String(length=512), nullable=True),
    sa.Column('protocol', sa.String(length=10), nullable=False),
    sa.Column('snmp_version', sa.String(length=5), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=True),
    sa.Column('report_name', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_reports_schedule_id'), 'generated_reports', ['schedule_id'], unique=False)
    op.create_table('kpi_thresholds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('kpi_type', sa.String(length=50), nullable=False),
    sa.Column('technology', sa.String(length=50), nullable=True),
    sa.Column('operator', sa.String(length=4), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('clear_value', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('consecutive_samples', sa.Integer(), nullable=False),
    sa.Column('auto_clear', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kpi_thresholds_kpi_type'), 'kpi_thresholds', ['kpi_type'], unique=False)
    op.create_table('mibs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('oid_root', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monitoring_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('policy_type', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('interval_seconds', sa.Integer(), nullable=False),
    sa.Column('target_all_devices', sa.Boolean(), nullable=False),
    sa.Column('device_ids', sa.JSON(), nullable=False),
    sa.Column('metric_oids', sa.JSON(), nullable=False),
    sa.Column('thresholds', sa.JSON(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=20), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('report_name', sa.String(length=64), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('cadence', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('retain_last', sa.Integer(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=20), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('device_type', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('vendor', sa.String(length=100), nullable=True),
    sa.Column('os_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('site_id', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('lifecycle_state', sa.String(length=50), nullable=False),
    sa.Column('platform_family', sa.String(length=100), nullable=True),
    sa.Column('mgmt_vrf', sa.String(length=100), nullable=True),
    sa.Column('snmp_enabled', sa.Boolean(), nullable=False),
    sa.Column('ssh_enabled', sa.Boolean(), nullable=False),
    sa.Column('telemetry_enabled', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('credential_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_address')
    )
    op.create_index(op.f('ix_devices_platform_family'), 'devices', ['platform_family'], unique=False)
    op.create_index(op.f('ix_devices_role'), 'devices', ['role'], unique=False)
    op.create_index(op.f('ix_devices_site_id'), 'devices', ['site_id'], unique=False)
    op.create_table('alarms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('source_host', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('trap_oid', sa.String(length=255), nullable=True),
    sa.Column('raw_varbinds', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('correlation_key', sa.String(length=255), nullable=False),
    sa.Column('dedup_key', sa.String(length=255), nullable=True),
    sa.Column('correlation_group_id', sa.UUID(), nullable=True),
    sa.Column('root_alarm_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('object_type', sa.String(length=50), nullable=True),
    sa.Column('object_id', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cleared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ack_by', sa.String(length=255), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['root_alarm_id'], ['alarms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alarms_correlation_group_id'), 'alarms', ['correlation_group_id'], unique=False)
    op.create_index(op.f('ix_alarms_correlation_key'), 'alarms', ['correlation_key'], unique=False)
    op.create_index('ix_alarms_correlation_state', 'alarms', ['correlation_key', 'state'], unique=False)
    op.create_index(op.f('ix_alarms_dedup_key'), 'alarms', ['dedup_key'], unique=False)
    op.create_index(op.f('ix_alarms_device_id'), 'alarms', ['device_id'], unique=False)
    op.create_index('ix_alarms_device_state', 'alarms', ['device_id', 'state'], unique=False)
    op.create_index(op.f('ix_alarms_object_id'), 'alarms', ['object_id'], unique=False)
    op.create_index('ix_alarms_severity', 'alarms', ['severity'], unique=False)
    op.create_index(op.f('ix_alarms_source_host'), 'alarms', ['source_host'], unique=False)
    op.create_table('commands',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cli_command', sa.Text(), nullable=False),
    sa.Column('output_path', sa.String(length=500), nullable=True),
    sa.Column('last_output', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credential_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('credential_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'credential_id', 'purpose', name='uq_credential_assignment')
    )
    op.create_table('interfaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('if_index', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('alias', sa.String(length=512), nullable=True),
    sa.Column('mac_address', sa.String(length=64), nullable=True),
    sa.Column('admin_status', sa.String(length=30), nullable=True),
    sa.Column('oper_status', sa.String(length=30), nullable=True),
    sa.Column('speed_bps', sa.BigInteger(), nullable=True),
    sa.Column('interface_type', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interfaces_device_id'), 'interfaces', ['device_id'], unique=False)
    op.create_index('ix_interfaces_device_ifindex', 'interfaces', ['device_id', 'if_index'], unique=True)
    op.create_index('ix_interfaces_device_name', 'interfaces', ['device_id', 'name'], unique=False)
    op.create_index('ix_interfaces_oper_status', 'interfaces', ['oper_status'], unique=False)
    op.create_table('inventory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.Column('firmware_version', sa.String(length=255), nullable=True),
    sa.Column('hardware_model', sa.String(length=255), nullable=True),
    sa.Column('interfaces_count', sa.Integer(), nullable=True),
    sa.Column('cpu_cores', sa.Integer(), nullable=True),
    sa.Column('memory_total', sa.Integer(), nullable=True),
    sa.Column('memory_free', sa.Integer(), nullable=True),
    sa.Column('uptime_seconds', sa.Integer(), nullable=True),
    sa.Column('port_count', sa.Integer(), nullable=True),
    sa.Column('additional_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id')
    )
    op.create_table('ios_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('image_file', sa.String(length=500), nullable=True),
    sa.Column('version', sa.String(length=255), nullable=True),
    sa.Column('platform', sa.String(length=100), nullable=True),
    sa.Column('boot_image', sa.String(length=500), nullable=True),
    sa.Column('uptime_hours', sa.Integer(), nullable=True),
    sa.Column('is_eol', sa.Boolean(), nullable=False),
    sa.Column('is_eos', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kpis',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('kpi_type', sa.String(length=50), nullable=False),
    sa.Column('metric_name', sa.String(length=255), nullable=True),
    sa.Column('technology', sa.String(length=50), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('kpi_area', sa.String(length=50), nullable=True),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('object_type', sa.String(length=50), nullable=False),
    sa.Column('object_id', sa.String(length=255), nullable=True),
    sa.Column('quality', sa.String(length=30), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('labels', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_kpis_device_timestamp', 'kpis', ['device_id', 'timestamp'], unique=False)
    op.create_index('ix_kpis_kpi_type', 'kpis', ['kpi_type'], unique=False)
    op.create_index(op.f('ix_kpis_metric_name'), 'kpis', ['metric_name'], unique=False)
    op.create_index(op.f('ix_kpis_object_id'), 'kpis', ['object_id'], unique=False)
    op.create_index('ix_kpis_object_timestamp', 'kpis', ['object_type', 'object_id', 'timestamp'], unique=False)
    op.create_index('ix_kpis_source_timestamp', 'kpis', ['source_type', 'timestamp'], unique=False)
    op.create_index('ix_kpis_timestamp', 'kpis', ['timestamp'], unique=False)
    op.create_table('topology_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.String(length=255), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('position_x', sa.Float(), nullable=True),
    sa.Column('position_y', sa.Float(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id')
    )
    op.create_table('topology_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_node_id', sa.UUID(), nullable=False),
    sa.Column('target_node_id', sa.UUID(), nullable=False),
    sa.Column('source_interface', sa.String(length=100), nullable=True),
    sa.Column('target_interface', sa.String(length=100), nullable=True),
    sa.Column('discovery_method', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_node_id'], ['topology_nodes.id'], ),
    sa.ForeignKeyConstraint(['target_node_id'], ['topology_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topology_links')
    op.drop_table('topology_nodes')
    op.drop_index('ix_kpis_timestamp', table_name='kpis')
    op.drop_index('ix_kpis_source_timestamp', table_name='kpis')
    op.drop_index('ix_kpis_object_timestamp', table_name='kpis')
    op.drop_index(op.f('ix_kpis_object_id'), table_name='kpis')
    op.drop_index(op.f('ix_kpis_metric_name'), table_name='kpis')
    op.drop_index('ix_kpis_kpi_type', table_name='kpis')
    op.drop_index('ix_kpis_device_timestamp', table_name='kpis')
    op.drop_table('kpis')
    op.drop_table('ios_versions')
    op.drop_table('inventory')
    op.drop_index('ix_interfaces_oper_status', table_name='interfaces')
    op.drop_index('ix_interfaces_device_name', table_name='interfaces')
    op.drop_index('ix_interfaces_device_ifindex', table_name='interfaces')
    op.drop_index(op.f('ix_interfaces_device_id'), table_name='interfaces')
    op.drop_table('interfaces')
    op.drop_table('credential_assignments')
    op.drop_table('commands')
    op.drop_index(op.f('ix_alarms_source_host'), table_name='alarms')
    op.drop_index('ix_alarms_severity', table_name='alarms')
    op.drop_index(op.f('ix_alarms_object_id'), table_name='alarms')
    op.drop_index('ix_alarms_device_state', table_name='alarms')
    op.drop_index(op.f('ix_alarms_device_id'), table_name='alarms')
    op.drop_index(op.f('ix_alarms_dedup_key'), table_name='alarms')
    op.drop_index('ix_alarms_correlation_state', table_name='alarms')
    op.drop_index(op.f('ix_alarms_correlation_key'), table_name='alarms')
    op.drop_index(op.f('ix_alarms_correlation_group_id'), table_name='alarms')
    op.drop_table('alarms')
    op.drop_index(op.f('ix_devices_site_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_role'), table_name='devices')
    op.drop_index(op.f('ix_devices_platform_family'), table_name='devices')
    op.drop_table('devices')
    op.drop_table('system_settings')
    op.drop_table('report_schedules')
    op.drop_table('monitoring_policies')
    op.drop_table('mibs')
    op.drop_index(op.f('ix_kpi_thresholds_kpi_type'), table_name='kpi_thresholds')
    op.drop_table('kpi_thresholds')
    op.drop_index(op.f('ix_generated_reports_schedule_id'), table_name='generated_reports')
    op.drop_table('generated_reports')
    op.drop_table('credentials')
    op.drop_index('ix_audit_log_timestamp', table_name='audit_log')
    op.drop_index('ix_audit_log_object', table_name='audit_log')
    op.drop_index('ix_audit_log_actor_action', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_app_users_username'), table_name='app_users')
    op.drop_table('app_users')
    op.drop_index(op.f('ix_app_roles_name'), table_name='app_roles')
    op.drop_table('app_roles')
    op.drop_index('ix_alarm_rules_source_type', table_name='alarm_rules')
    op.drop_index('ix_alarm_rules_enabled_priority', table_name='alarm_rules')
    op.drop_table('alarm_rules')
    # ### end Alembic commands ###
